version: '3.8'
services:
    events_service:
        build: .
        container_name: events_service
        ports:
            - '8080:8080'
        networks:
            - app_network

    artillery:
        image: artilleryio/artillery
        container_name: artillery
        volumes:
            - .:/app
        working_dir: /app
        networks:
            - app_network
        stdin_open: true
        tty: true

networks:
    app_network:
        driver: bridge
